### ISSUE TITLE
It requires `pytest-runner` for build

### ISSUE THREAD

**Issue by catap** [MatthiasValvekens/certomancer#10]
Let me quote `pyproject.toml`:
```
[build-system]
requires = [
    "setuptools>=67.4",
    "wheel", "pytest-runner",
]
```
is it really required to build it, not test?

**Comment by MatthiasValvekens** [comment]
This used to be a requirement for being able to use `setup.py test`. But direct `setup.py` invocation is deprecated anyway, so it can probably be removed. I think this is mostly a leftover from the automatic migration to `pyproject.toml`.

**Comment by catap** [comment]
Thanks for very fast fix!

**Comment by catap** [comment]
The same issue exists at https://github.com/MatthiasValvekens/certvalidator and https://github.com/MatthiasValvekens/pyHanko at least
