### ISSUE TITLE
Consider adding a py.typed file to the package

### ISSUE THREAD

**Issue by peteris-zealid** [MatthiasValvekens/certomancer#2]
Hello,

I ran `mypy` on the codebase and it revealed only a few minor issues. Nothing that the end user would ever care about. On one hand it might be slightly irresponsible to add a py.typed marker without setting up a type checker to run at each commit, but on the other hand automatically generated stubs will be of much lower quality and should be avoided for practical purposes.

**Comment by MatthiasValvekens** [comment]
Hi @peteris-zealid,

Sorry, took me a while to get to this one. I added `py.typed`, fixed all the mypy warnings and added a mypy checker workflow to the repo :). See linked PR.

**Comment by peteris-zealid** [comment]
Hi, I thought this was a closed issue, but thank you for letting me know. Sometimes it pains my heart to see you not getting paid for all the quality work (and support) you are doing on this lib.

**Comment by MatthiasValvekens** [comment]
Well, my GitHub Sponsors registration request finally got processed yesterday, so there's an avenue now... ;)

Not that I have grand expectations about the revenue that would generate, though :)
