### ISSUE TITLE
pypi package contains tests but missed tests/data

### ISSUE THREAD

**Issue by catap** [MatthiasValvekens/certomancer#9]
The last version of certomancer on pypi contains tests but an attempt to run it failed, because it had missed `tests/data` folder.

Shall `tests/data` be included into package?

**Comment by MatthiasValvekens** [comment]
That's strange; the `pyproject.toml` file should have been set up to exclude tests altogether---there's an argument to be made for including them in source dists, but given that certomancer only ships with universal wheels, there's not much point to that.

I don't have much time to look into this now, but this is what I want:

 - The source dist should either not include any tests, or include tests + test data.
 - The wheels should most definitely NOT include any tests---if they do, it potentially causes all sorts of havoc at runtime.

Apparently the first condition is currently not met, but I'd have to look up how to deal with this without breaking the wheels (which are far more important).

**Comment by catap** [comment]
Just a proof that it really has tests without data:
```
√ /tmp % cd xzy/
√ xzy % wget https://files.pythonhosted.org/packages/94/64/8dbc2e51612c1a6ea43d98c73dd65d0c30e98ff83e1a7ab80f5a4502eb6f/certomancer-0.11.0.tar.gz 
--2023-12-18 01:46:25--  https://files.pythonhosted.org/packages/94/64/8dbc2e51612c1a6ea43d98c73dd65d0c30e98ff83e1a7ab80f5a4502eb6f/certomancer-0.11.0.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 146.75.116.223
Connecting to files.pythonhosted.org (files.pythonhosted.org)|146.75.116.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74450 (73K) [application/octet-stream]
Saving to: ‘certomancer-0.11.0.tar.gz’

certomancer-0.11.0.tar.gz            100%[===================================================================>]  72.71K  --.-KB/s    in 0.03s   

2023-12-18 01:46:25 (2.17 MB/s) - ‘certomancer-0.11.0.tar.gz’ saved [74450/74450]

√ xzy % tar xzf certomancer-0.11.0.tar.gz   
√ xzy % ls certomancer-0.11.0/                                                                                                                                           
LICENSE			PKG-INFO		README.md		certomancer		certomancer.egg-info	pyproject.toml		setup.cfg		tests
√ xzy % ls certomancer-0.11.0/tests/
test_animator.py	test_certs.py		test_services.py	test_utils.py
√ xzy %                             
```

**Comment by catap** [comment]
ping
